**Import Basic Libraries**

In [1]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Iris.csv')
df.head()

Saving Iris.csv to Iris.csv


,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


**Iris Flowers Measurements**

In [2]:
import pandas as pd

# Features (measurements)
feature_names = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
X = df[feature_names]

# Target (flower type)
y = df['Species']

# Create a new DataFrame with features and target for better understanding
df_processed = pd.DataFrame(X, columns=feature_names)
df_processed['species'] = y

print(df_processed.head())

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa


In [3]:
print(df_processed[df_processed['species'] == 'Iris-versicolor'].head())
print(df_processed[df_processed['species'] == 'Iris-virginica'].head())

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          species
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
53            5.5           2.3            4.0           1.3  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor
     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         species
100            6.3           3.3            6.0           2.5  Iris-virginica
101            5.8           2.7            5.1           1.9  Iris-virginica
102            7.1           3.0            5.9           2.1  Iris-virginica
103            6.3           2.9            5.6           1.8  Iris-virginica
104            6.5           3.0            5.8           2.2  Iris-virginica


**Machine Learning Model**

In [4]:
# Import
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Load data
iris = load_iris()
X = iris.data      # measurements
y = iris.target    # species

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Test prediction
predictions = model.predict(X_test)

print(predictions)

[2 0 0 0 1 0 1 1 0 2 0 2 1 2 2 2 2 1 0 1 1 1 1 2 2 2 2 0 0 2]


**Accuracy**

In [6]:
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, predictions))

Accuracy: 0.9666666666666667


**Performance**

In [8]:
from sklearn.metrics import classification_report, confusion_matrix

# Detailed performance
print("\nClassification Report:\n", classification_report(y_test, predictions))

# Confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, predictions))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.90      0.95        10
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30


Confusion Matrix:
 [[ 9  0  0]
 [ 0  9  1]
 [ 0  0 11]]


**Basic Classification Concept** in Machine Learning

Classification is when a model learns to assign a label (category) to data.

Input → flower measurements (length & width)

Output → species:
Setosa, Versicolor and Virginica

**Types of Classification**

There are 2 types of classification **Binary** and **Multi-class** Classification. Binary means only 2 classes and Multi-class means more than 2 classes such as Iris dataset (3 flowers).

**Features** is known as (X) the input data such as sepal length, petal width while **Target/Label** is known as (y) which refers to the output.

**Training Data** is used to teach the model while **Testing Data** is used to check performance.

**Performance** is checked through **Accuracy** which shows the percentage of the correct prediction.

**Confusion Matrix** shows the correct and wrong predictions.